language: php
sudo: false
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
branches:
  except:
    - v0.5
    - v0.6
    - v0.6-PHP_5.2
    - documentation
services: redis-server
before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
script:
  - vendor/bin/phpunit -c phpunit.xml.travisci
matrix:
  fast_finish: true
