# GitHub Action for Predis with PHP 7.2, 7.3, 7.4 & 8.0 & Redis 3, 4, 5 & 6
name: Predis Builds
on: [push, pull_request]
jobs:
  predis:
    name: Redis ${{ matrix.redis-versions }} (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:${{ matrix.redis-versions }}
        ports:
        - 6379/tcp
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.3', '7.4', '8.0']
        redis-versions: ['3', '4', '5', '6']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup PHP, with composer and extensions
      with:
        php-version: ${{ matrix.php-versions }}
      uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
    - name: Get composer cache directory
      id: composercache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    - name: Cache composer dependencies
      uses: actions/cache@v2
      with:
        php-version: ${{ matrix.php-versions }}
        path: ${{ steps.composercache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader
    - name: Test with phpunit
      run: vendor/bin/phpunit
